# Generated by Django 3.2.9 on 2022-02-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('O', 'Operativo'), ('A', 'Administrativo')], max_length=50, verbose_name='Area')),
            ],
        ),
    ]
